apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dutyguild
  namespace: dutyguild
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dutyguild.ru
      secretName: dutyguild-tls
  rules:
    - host: dutyguild.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dutyguild
                port:
                  number: 80
